### ISSUE TITLE
Suggest doing a docker build, then docker up

### ISSUE THREAD

**Issue by ryjones** [cyberscribbleorg/EventFlow#4]
I'm finding the docker injector doesn't build correctly from docker compose up. if I do a docker build injector first, it works.

**Comment by cyberscribbleorg** [comment]
- Can you share your docker version and docker-compose version ?
- What error message are you seeing during the docker compose up? 

In the mean time I have modified the README to do a docker compose build followed by docker compose up

**Comment by ryjones** [comment]
```
docker --version

Docker version 24.0.5, build ced0996
```
